### ISSUE TITLE
Code Does not Compiles

### ISSUE THREAD

**Issue by arashraf** [stiers/Cynics#1]
Hi, I am studying the project just to learn the programming, but i have found out that the code does not compiled and there are several missed classes.

**Comment by sti-lyneos** [comment]
Please use Visual Studio 2005 SP1 and Visual Studio 2008 to compile. Or re-download the source [from this link](http://www.cynics-soft.com/sign-up-general-ledger-source-code-evaluation.html)

**Comment by JLTLC** [comment]
I tried to compile it but it is missing CSCommon.dll.  I do have the dll.  Contact me to get it put into the project.
